apiVersion: operator.dataverse.redhat.com/v1alpha1
kind: SnowflakeAccount
metadata:
  labels:
    app.kubernetes.io/name: speck
    app.kubernetes.io/managed-by: kustomize
  name: snowflakeaccount-sample
spec:
  # TODO(user): Add fields here
